version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: starburger
      POSTGRES_USER: evgenijsozykin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: evgeny1337depo/star-burger-backend:latest
    environment:
      - DATABASE_URL=postgresql://evgenijsozykin:${POSTGRES_PASSWORD}@db:5432/starburger
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - media_volume:/app/media
      - staticfiles_volume:/app/staticfiles
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: evgeny1337depo/star-burger-frontend:latest
    ports:
      - "127.0.0.1:3000:3000"


volumes:
  postgres_data:
  media_volume:
  staticfiles_volume:
