services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: starburger
      POSTGRES_USER: evgenijsozykin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: evgeny1337depo/star-burger-backend:latest
    environment:
      - DATABASE_URL=postgresql://evgenijsozykin:${POSTGRES_PASSWORD}@db:5432/starburger
    env_file:
      - .env
    volumes:
      - media_volume:/app/media
      - staticfiles_volume:/app/staticfiles
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: evgeny1337depo/star-burger-frontend:latest

  nginx:
    build: ./nginx
    image: evgeny1337depo/star-burger-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  media_volume:
  staticfiles_volume:
